import {
  CrossEncoderCandidate,
  CrossEncoderConfig,
  CrossEncoderQuery,
  CrossEncoderResult,
} from './types';

/**
 * Computes Jaccard similarity between two string arrays or sets.
 */
function jaccardSimilarity(a?: string[], b?: string[]): number {
  if (!a || !b || a.length === 0 || b.length === 0) return 0;
  const setA = new Set(a.map((s) => s.toLowerCase().trim()));
  const setB = new Set(b.map((s) => s.toLowerCase().trim()));
  let intersection = 0;
  for (const item of setA) {
    if (setB.has(item)) intersection++;
  }
  const union = setA.size + setB.size - intersection;
  return union > 0 ? intersection / union : 0;
}

/**
 * Tokenizes a string into lowercased alphanumeric words.
 */
function tokenize(text?: string): string[] {
  if (!text) return [];
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, ' ')
    .split(/\s+/)
    .filter((w) => w.length > 1);
}

/**
 * Sigmoid activation with temperature scaling.
 */
function sigmoid(x: number, temperature: number): number {
  const scaled = x / Math.max(0.01, temperature);
  return 1.0 / (1.0 + Math.exp(-Math.max(-20, Math.min(20, scaled))));
}

/**
 * CrossEncoderRanker performs deep cross-scoring on top-K retrieved candidates.
 *
 * In contrast to Bi-Encoders which only compute independent vector dot-products,
 * the Cross-Encoder directly analyzes joint token overlap, category-tag alignment,
 * and element-wise interaction vectors ([u; v; |u-v|; u*v]) to eliminate false-positive
 * semantic matches before diversity re-ranking.
 */
export class CrossEncoderRanker {
  private readonly config: CrossEncoderConfig;

  /**
   * Initializes the CrossEncoderRanker.
   *
   * @param config - Hyperparameter overrides
   */
  constructor(config?: Partial<CrossEncoderConfig>) {
    this.config = {
      crossWeight: config?.crossWeight ?? 0.6,
      attributeWeight: config?.attributeWeight ?? 0.25,
      temperature: config?.temperature ?? 1.0,
    };
  }

  /**
   * Computes joint feature vector interaction between query and candidate embeddings.
   * Models [u; v; |u - v|; u * v] non-linear alignment.
   */
  private computeInteractionScore(u: Float32Array, v: Float32Array): number {
    const dim = Math.min(u.length, v.length);
    if (dim === 0) return 0.5;

    let dotSum = 0;
    let normUSq = 0;
    let normVSq = 0;
    let diffSum = 0;

    for (let i = 0; i < dim; i++) {
      const ui = u[i];
      const vi = v[i];
      dotSum += ui * vi;
      normUSq += ui * ui;
      normVSq += vi * vi;
      diffSum += Math.abs(ui - vi);
    }

    const denom = Math.sqrt(normUSq) * Math.sqrt(normVSq);
    const cosSim = denom > 1e-12 ? dotSum / denom : 0;
    const meanDiff = diffSum / dim;

    // Logit combining high directional alignment (cosSim) with low elementwise variance (meanDiff)
    const logit = 3.0 * cosSim - 1.0 * meanDiff;
    return sigmoid(logit, this.config.temperature);
  }

  /**
   * Re-ranks candidate items using joint cross-encoder interactions.
   *
   * @param query - Target query or seed item with embedding and metadata
   * @param candidates - Pool of candidate items generated by Stage-1 retrieval
   * @returns Array of CrossEncoderResult sorted descending by blendedScore
   */
  public rank(query: CrossEncoderQuery, candidates: CrossEncoderCandidate[]): CrossEncoderResult[] {
    const queryTokens = tokenize(query.title);
    const results: CrossEncoderResult[] = [];

    for (const cand of candidates) {
      // 1. Joint embedding interaction
      const crossScore = this.computeInteractionScore(query.embedding, cand.embedding);

      // 2. Lexical token overlap
      const candTokens = tokenize(cand.title);
      const tokenOverlap = jaccardSimilarity(queryTokens, candTokens);

      // 3. Category & tag alignment
      const tagOverlap = jaccardSimilarity(query.tags, cand.tags);
      const catMatch =
        query.category && cand.category && query.category.toLowerCase() === cand.category.toLowerCase()
          ? 1.0
          : 0.0;

      const attributeScore = 0.5 * catMatch + 0.3 * tagOverlap + 0.2 * tokenOverlap;

      // 4. Combined fine-grained cross score
      const refinedCross =
        (1 - this.config.attributeWeight) * crossScore + this.config.attributeWeight * attributeScore;

      // 5. Blended score between Stage-1 baseScore and Stage-2 refinedCross
      const blendedScore =
        (1 - this.config.crossWeight) * cand.baseScore + this.config.crossWeight * refinedCross;

      results.push({
        id: cand.id,
        crossScore: Math.round(crossScore * 1000) / 1000,
        baseScore: Math.round(cand.baseScore * 1000) / 1000,
        blendedScore: Math.round(blendedScore * 1000) / 1000,
        tokenOverlap: Math.round(tokenOverlap * 1000) / 1000,
      });
    }

    results.sort((a, b) => b.blendedScore - a.blendedScore);
    return results;
  }
}
